name: first-workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: echo "this is lint running"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "this is test running"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: echo "this is build running"
